Refactor code to conditionally set headers based on request credentials
samagra-comms/uci-apis pull request #161
Opened 2023-07-04 16:09 UTC by RyanWalker277

2023-07-06 06:41 UTC, chinmoy12c commented
Please create a ticket for this and tag this PR to the ticket.

2023-07-06 06:43 UTC, chinmoy12c requested changes

2023-07-06 06:43 UTC, chinmoy12c commented on src/modules/service/http-get.resolver.ts
> +    if (!getRequestConfig.credentials && Object.keys(getRequestConfig.credentials).length != 0) {
`if(!getRequestConfig.credentials) => if(getRequestConfig.credentials)`

2023-07-06 17:12 UTC, RyanWalker277 commented
Changes done. @chinmoy12c please review.

2023-07-10 06:08 UTC, chinmoy12c approved these changes

2023-07-10 06:08 UTC, merged